export const cards = [
    {
        image: '../images/image_1.jpg',
        name: 'Новогодний набор Домик "Уютная компания"',
        pack: 'хэк',
        weight: '400',
        price_xs: '322,0',
        price_s: '308,4',
        price_m: '296,1',
        price_l: '284,8',
        price_xl: '274,5',
    },
    {
        image: '../images/image_2.png',
        name: 'Новогодний набор "Портфель"',
        pack: 'хэк',
        weight: '400',
        price_xs: '322,0',
        price_s: '308,4',
        price_m: '296,1',
        price_l: '284,8',
        price_xl: '274,5',
    },
    {
        image: '../images/image_3.png',
        name: 'Новогодний набор "Сказки Деда Мороза"',
        pack: 'хэк',
        weight: '400',
        price_xs: '314,0',
        price_s: '300,4',
        price_m: '288,1',
        price_l: '276,8',
        price_xl: '266,5',
    },
    {
        image: '../images/image_4.png',
        name: 'Новогодний набор "Фонарик резной"',
        pack: 'хэк',
        weight: '400',
        price_xs: '312,0',
        price_s: '298,4',
        price_m: '286,1',
        price_l: '274,8',
        price_xl: '264,5',
    },
    {
        image: '../images/image_5.png',
        name: 'Новогодний набор "Кристалл Искорка"',
        pack: 'хэк',
        weight: '400',
        price_xs: '312,0',
        price_s: '298,4',
        price_m: '286,1',
        price_l: '274,8',
        price_xl: '264,5',
    },
    {
        image: '../images/image_6.png',
        name: 'Новогодний набор "Загадки от деда Мороза"',
        pack: 'хэк',
        weight: '400',
        price_xs: '312,0',
        price_s: '298,4',
        price_m: '286,1',
        price_l: '274,8',
        price_xl: '264,5',
    },
    {
        image: '../images/image_7.png',
        name: 'Новогодний набор "Дед Мороз и снегурочка с кормушкой"',
        pack: 'хэк',
        weight: '500',
        price_xs: '369,0',
        price_s: '352,8',
        price_m: '338,1',
        price_l: '324,7',
        price_xl: '312,3',
    },
    {
        image: '../images/image_8.png',
        name: 'Новогодний набор "Снежинка малая"',
        pack: 'хэк',
        weight: '500',
        price_xs: '374,0',
        price_s: '357,8',
        price_m: '343,1',
        price_l: '329,7',
        price_xl: '317,3',
    },
    {
        image: '../images/image_10.png',
        name: 'Новогодний набор "Снежинка-ежинка малая"',
        pack: 'хэк',
        weight: '500',
        price_xs: '374',
        price_s: '357,8',
        price_m: '343,1',
        price_l: '329,7',
        price_xl: '317,3',
    },
    {
        image: '../images/image_11.png',
        name: 'Новогодний набор "Елочка малая"',
        pack: 'хэк',
        weight: '500',
        price_xs: '369,0',
        price_s: '352,8',
        price_m: '338,1',
        price_l: '324,7',
        price_xl: '312,3',
    },
    {
        image: '../images/image_12.png',
        name: 'Новогодний набор "Подарок "Тигриная история"',
        pack: 'микрогофрокартон',
        weight: '600',
        price_xs: '483,0',
        price_s: '462,7',
        price_m: '444,3',
        price_l: '427,4',
        price_xl: '412,0',
    },
    {
        image: '../images/image_13.png',
        name: 'Новогодний набор "Подарок "Рыжие обнимашки"',
        pack: 'микрогофрокартон',
        weight: '600',
        price_xs: '483,0',
        price_s: '462,7',
        price_m: '444,3',
        price_l: '427,4',
        price_xl: '412,0',
    },
    {
        image: '../images/image_15.png',
        name: 'Новогодний набор "Милашки"',
        pack: 'микрогофрокартон',
        weight: '600',
        price_xs: '483,0',
        price_s: '462,7',
        price_m: '444,3',
        price_l: '427,4',
        price_xl: '412,0',
    },
    {
        image: '../images/image_16.png',
        name: 'Новогодний набор "Лабиринт"',
        pack: 'микрогофрокартон',
        weight: '600',
        price_xs: '483,0',
        price_s: '462,7',
        price_m: '444,3',
        price_l: '427,4',
        price_xl: '412,0',
    },
    {
        image: '../images/image_17.png',
        name: 'Новогодний набор "Часы каминные"',
        pack: 'микрогофрокартон',
        weight: '600',
        price_xs: '503,0',
        price_s: '482,7',
        price_m: '464,3',
        price_l: '447,4',
        price_xl: '432,0',
    },
    {
        image: '../images/image_18.png',
        name: 'Новогодний подарок "Ларец "Под елкой"',
        pack: 'микрогофрокартон',
        weight: '700',
        price_xs: '633,0',
        price_s: '606,9',
        price_m: '583,1',
        price_l: '561,4',
        price_xl: '541,5',
    },
    {
        image: '../images/image_19.png',
        name: 'Новогодний подарок "Ларец "Скорость"',
        pack: 'микрогофрокартон',
        weight: '700',
        price_xs: '633,0',
        price_s: '606,9',
        price_m: '583,1',
        price_l: '561,4',
        price_xl: '541,5',
    },
    {
        image: '../images/image_20.png',
        name: 'Новогодний подарок "Снежные кружева"',
        pack: 'микрогофрокартон',
        weight: '700',
        price_xs: '633,0',
        price_s: '606,9',
        price_m: '583,1',
        price_l: '561,4',
        price_xl: '541,5',
    },
    {
        image: '../images/image_21.png',
        name: 'Новогодний подарок "Сундук сказочный"',
        pack: 'микрогофрокартон',
        weight: '800',
        price_xs: '714,0',
        price_s: '684,0',
        price_m: '656,6',
        price_l: '631,7',
        price_xl: '608,8',
    },
    {
        image: '../images/image_22.png',
        name: 'Новогодний подарок "Ларец "Под елкой"',
        pack: 'микрогофрокартон',
        weight: '800',
        price_xs: '717,0',
        price_s: '687,0',
        price_m: '659,6',
        price_l: '634,7',
        price_xl: '611,8',
    },
    {
        image: '../images/image_23.png',
        name: 'Новогодний подарок "Ларец "Скорость"',
        pack: 'микрогофрокартон',
        weight: '800',
        price_xs: '717,0',
        price_s: '687,0',
        price_m: '659,6',
        price_l: '634,7',
        price_xl: '611,8',
    },
    {
        image: '../images/image_24.png',
        name: 'Новогодний подарок "Снежные кружева"',
        pack: 'микрогофрокартон',
        weight: '800',
        price_xs: '717,0',
        price_s: '687,0',
        price_m: '659,6',
        price_l: '634,7',
        price_xl: '611,8',
    },
    {
        image: '../images/image_25.png',
        name: 'Новогодний подарок "Каравелла"',
        pack: 'микрогофрокартон',
        weight: '900',
        price_xs: '847',
        price_s: '811,4',
        price_m: '779,1',
        price_l: '749,6',
        price_xl: '722,5',
    },
    {
        image: '../images/image_26.png',
        name: 'Новогодний подарок "Рюкзак Енотик"',
        pack: 'микрогофрокартон',
        weight: '900',
        price_xs: '839,0',
        price_s: '803,4',
        price_m: '771,1',
        price_l: '741,6',
        price_xl: '714,5',
    },
    {
        image: '../images/image_27.png',
        name: 'Новогодний подарок "Рюкзак джинсовый"',
        pack: 'микрогофрокартон',
        weight: '900',
        price_xs: '839,0',
        price_s: '803,4',
        price_m: '771,1',
        price_l: '741,6',
        price_xl: '714,5',
    },
    {
        image: '../images/image_28.png',
        name: 'Новогодний подарок "Новогодний вокзал"',
        pack: 'микрогофрокартон',
        weight: '900',
        price_xs: '848,0',
        price_s: '812,4',
        price_m: '780,1',
        price_l: '750,6',
        price_xl: '723,5',
    },
    {
        image: '../images/image_29.png',
        name: 'Новогодний подарок "Чемоданчик Дед Мороз и Снегурочка"',
        pack: 'микрогофрокартон, пластиковая ручка',
        weight: '1000',
        price_xs: '887,0',
        price_s: '848,4',
        price_m: '813,4',
        price_l: '781,3',
        price_xl: '752,0',
    },
    {
        image: '../images/image_30.png',
        name: 'Новогодний подарок Сумочка "Дед Мороз и дети"',
        pack: 'микрогофрокартон',
        weight: '1000',
        price_xs: '897,0',
        price_s: '858,4',
        price_m: '823,4',
        price_l: '791,3',
        price_xl: '762,0',
    },
    {
        image: '../images/image_31.png',
        name: 'Новогодний подарок Сумочка "Тройка лошадей"',
        pack: 'микрогофрокартон',
        weight: '1000',
        price_xs: '897,0',
        price_s: '858,4',
        price_m: '823,4',
        price_l: '791,3',
        price_xl: '762,0',
    },
    {
        image: '../images/image_32.png',
        name: 'Новогодний подарок Сундук "Кораблик"',
        pack: 'микрогофрокартон',
        weight: '1000',
        price_xs: '896,0',
        price_s: '857,4',
        price_m: '822,4',
        price_l: '790,3',
        price_xl: '761,0',
    },
    {
        image: '../images/image_33.png',
        name: 'Новогодний подарок "Портфель Ночь"',
        pack: 'микрогофрокартон',
        weight: '1000',
        price_xs: '900,0',
        price_s: '861,4',
        price_m: '826,4',
        price_l: '794,3',
        price_xl: '765,0',
    },
    {
        image: '../images/image_34.png',
        name: 'Новогодний подарок "Портфель Зодиак"',
        pack: 'микрогофрокартон',
        weight: '1000',
        price_xs: '900,0',
        price_s: '861,4',
        price_m: '826,4',
        price_l: '794,3',
        price_xl: '765,0',
    },
    {
        image: '../images/image_35.png',
        name: 'Новогодний подарок "Палех"',
        pack: 'микрогофрокартон',
        weight: '1000',
        price_xs: '891,0',
        price_s: '852,4',
        price_m: '817,4',
        price_l: '785,3',
        price_xl: '756,0',
    },
    {
        image: '../images/image_36.png',
        name: 'Новогодний подарок Фургончик "Карамель"',
        pack: 'микрогофрокартон',
        weight: '1000',
        price_xs: '901,0',
        price_s: '862,4',
        price_m: '827,4',
        price_l: '795,3',
        price_xl: '766,0',
    },
    {
        image: '../images/image_37.png',
        name: 'Новогодний подарок Фургончик "Мороженое"',
        pack: 'микрогофрокартон',
        weight: '1000',
        price_xs: '901,0',
        price_s: '862,4',
        price_m: '827,4',
        price_l: '795,3',
        price_xl: '766,0',
    },
    {
        image: '../images/image_38.png',
        name: 'Новогодний подарок "Машина Фура красная"',
        pack: 'микрогофрокартон',
        weight: '1000',
        price_xs: '903,0',
        price_s: '864,4',
        price_m: '829,4',
        price_l: '797,3',
        price_xl: '768,0',
    },
    {
        image: '../images/image_39.png',
        name: 'Новогодний подарок "Фура Фанфары"',
        pack: 'микрогофрокартон',
        weight: '1000',
        price_xs: '903,0',
        price_s: '864,4',
        price_m: '829,4',
        price_l: '797,3',
        price_xl: '768,0',
    },
    {
        image: '../images/image_36.png',
        name: 'Новогодний подарок Фургончик "Карамель"',
        pack: 'микрогофрокартон',
        weight: '1200',
        price_xs: '1051,0',
        price_s: '1005,5',
        price_m: '964,1',
        price_l: '926,3',
        price_xl: '891,7',
    },
    {
        image: '../images/image_37.png',
        name: 'Новогодний подарок Фургончик "Мороженое"',
        pack: 'микрогофрокартон',
        weight: '1200',
        price_xs: '1051,0',
        price_s: '1005,5',
        price_m: '964,1',
        price_l: '926,3',
        price_xl: '891,7',
    },
    {
        image: '../images/image_41.png',
        name: 'Новогодний подарок "Машина Фура красная"',
        pack: 'микрогофрокартон',
        weight: '1200',
        price_xs: '1053,0',
        price_s: '1007,5',
        price_m: '966,1',
        price_l: '928,3',
        price_xl: '893,7',
    },
    {
        image: '../images/image_42.png',
        name: 'Новогодний подарок "Фура Фанфары"',
        pack: 'микрогофрокартон',
        weight: '1200',
        price_xs: '1053,0',
        price_s: '1007,5',
        price_m: '966,1',
        price_l: '928,3',
        price_xl: '893,7',
    },
    {
        image: '../images/image_45.png',
        name: 'Новогодний подарок Замок "Снежная королева"',
        pack: 'микрогофрокартон',
        weight: '1200',
        price_xs: '1070,0',
        price_s: '1024,5',
        price_m: '983,1',
        price_l: '945,3',
        price_xl: '910,7',
    },
    {
        image: '../images/image_44.png',
        name: 'Новогодний подарок Замок "Вафелька"',
        pack: 'микрогофрокартон',
        weight: '1200',
        price_xs: '1070,0',
        price_s: '1024,5',
        price_m: '983,1',
        price_l: '945,3',
        price_xl: '910,7',
    },
    {
        image: '../images/image_45.png',
        name: 'Новогодний подарок Замок "Снежная королева"',
        pack: 'микрогофрокартон',
        weight: '1500',
        price_xs: '1289,0',
        price_s: '1233,3',
        price_m: '1182,7',
        price_l: '1136,5',
        price_xl: '1094,2',
    },
    {
        image: '../images/image_44.png',
        name: 'Новогодний подарок Замок "Вафелька"',
        pack: 'микрогофрокартон',
        weight: '1500',
        price_xs: '1289,0',
        price_s: '1233,3',
        price_m: '1182,7',
        price_l: '1136,5',
        price_xl: '1094,2',
    },
    {
        image: '../images/image_47.png',
        name: 'Новогодний подарок "Открытка"',
        pack: 'жесть',
        weight: '400',
        price_xs: '571,0',
        price_s: '557,4',
        price_m: '545,1',
        price_l: '533,8',
        price_xl: '523,5',
    },
    {
        image: '../images/image_48.png',
        name: 'Новогодний подарок "Золотой Петушок"',
        pack: 'жесть',
        weight: '400',
        price_xs: '493,0',
        price_s: '479,4',
        price_m: '467,1',
        price_l: '455,8',
        price_xl: '445,5',
    },
    {
        image: '../images/image_49.png',
        name: 'Новогодний подарок "Снеговик"',
        pack: 'жесть',
        weight: '400',
        price_xs: '576,0',
        price_s: '562,4',
        price_m: '550,1',
        price_l: '538,8',
        price_xl: '528,5',
    },
    {
        image: '../images/image_50.png',
        name: 'Новогодний подарок. НОВИНКА!! "Лото" внутри игра "ЛОТО"',
        pack: 'жесть',
        weight: '500',
        price_xs: '1390',
        price_s: '1373,8',
        price_m: '1359,1',
        price_l: '1345,7',
        price_xl: '1333,3',
    },
    {
        image: '../images/image_52.png',
        name: 'Новогодний подарок "Почтальон"',
        pack: 'жесть',
        weight: '600',
        price_xs: '588,0',
        price_s: '567,7',
        price_m: '549,3',
        price_l: '532,4',
        price_xl: '517,0',
    },
    {
        image: '../images/image_53.png',
        name: 'Новогодний подарок "Шкатулка"',
        pack: 'жесть',
        weight: '600',
        price_xs: '747,0',
        price_s: '726,7',
        price_m: '708,3',
        price_l: '691,4',
        price_xl: '676,0',
    },
    {
        image: '../images/image_54.png',
        name: 'Новогодний подарок "Книга "Снежная королева"',
        pack: 'жесть',
        weight: '600',
        price_xs: '776,0',
        price_s: '755,7',
        price_m: '737,3',
        price_l: '720,4',
        price_xl: '705,0',
    },
    {
        image: '../images/image_55.png',
        name: 'Новогодний подарок Саквояж"Прогулка"',
        pack: 'жесть с конгревом',
        weight: '600',
        price_xs: '785,0',
        price_s: '764,7',
        price_m: '746,3',
        price_l: '729,4',
        price_xl: '714,0',
    },
    {
        image: '../images/image_56.png',
        name: 'Новогодний подарок "Зимний фонарик"',
        pack: 'жесть',
        weight: '700',
        price_xs: '780,0',
        price_s: '753,9',
        price_m: '730,1',
        price_l: '708,4',
        price_xl: '688,5',
    },
    {
        image: '../images/image_57.png',
        name: 'Новогодний подарок "Портфель "Рождество"',
        pack: 'жесть',
        weight: '700',
        price_xs: '832,0',
        price_s: '805,9',
        price_m: '782,1',
        price_l: '760,4',
        price_xl: '740,5',
    },
    {
        image: '../images/image_58.png',
        name: 'Новогодний подарок "Портфель "Мешок подарков"',
        pack: 'жесть',
        weight: '700',
        price_xs: '832,0',
        price_s: '805,9',
        price_m: '782,1',
        price_l: '760,4',
        price_xl: '740,5',
    },
    {
        image: '../images/image_59.png',
        name: 'Новогодний подарок "Детишки"',
        pack: 'жесть',
        weight: '700',
        price_xs: '832,0',
        price_s: '805,9',
        price_m: '782,1',
        price_l: '760,4',
        price_xl: '740,5',
    },
    {
        image: '../images/image_60.png',
        name: 'Новогодний подарок "Палех дед мороз"',
        pack: 'жесть с конгревом',
        weight: '700',
        price_xs: '838,0',
        price_s: '811,9',
        price_m: '788,1',
        price_l: '766,4',
        price_xl: '746,5',
    },
    {
        image: '../images/image_61.png',
        name: 'Новогодний подарок "Созвездие тигра"',
        pack: 'жесть',
        weight: '700',
        price_xs: '845,0',
        price_s: '818,0',
        price_m: '795,1',
        price_l: '773,4',
        price_xl: '753,5',
    },
    {
        image: '../images/image_62.png',
        name: 'Новогодний подарок "Овал Сказка"',
        pack: 'жесть',
        weight: '700',
        price_xs: '897,0',
        price_s: '867,0',
        price_m: '839,6',
        price_l: '814,7',
        price_xl: '791,8',
    },
    {
        image: '../images/image_63.png',
        name: 'Новогодний подарок "Винтаж"',
        pack: 'жесть',
        weight: '800',
        price_xs: '979,0',
        price_s: '949,0',
        price_m: '921,6',
        price_l: '896,7',
        price_xl: '873,8',
    },
    {
        image: '../images/image_64.png',
        name: 'Новогодний подарок "Бенгалия"',
        pack: 'жесть',
        weight: '900',
        price_xs: '1229,0',
        price_s: '1193,4',
        price_m: '1161,1',
        price_l: '1131,6',
        price_xl: '1104,5',
    },
    {
        image: '../images/image_65.png',
        name: 'Новогодний подарок "Карапузы"',
        pack: 'жесть',
        weight: '900',
        price_xs: '1015,0',
        price_s: '979,4',
        price_m: '947,1',
        price_l: '917,6',
        price_xl: '890,5',
    },
    {
        image: '../images/image_66.png',
        name: 'Новогодний подарок "Снежная королева"',
        pack: 'жесть',
        weight: '900',
        price_xs: '1050,0',
        price_s: '1014,4',
        price_m: '982,1',
        price_l: '952,6',
        price_xl: '925,5',
    },
    {
        image: '../images/image_67.png',
        name: 'Новогодний подарок "Сказки Деда Мороза"',
        pack: 'жесть',
        weight: '1000',
        price_xs: '1080,0',
        price_s: '1041,4',
        price_m: '1006,4',
        price_l: '974,3',
        price_xl: '945,0',
    },
    {
        image: '../images/image_68.png',
        name: 'Новогодний подарок Кейс "Палех Тройка"',
        pack: 'жесть',
        weight: '1000',
        price_xs: '1413,0',
        price_s: '1374,4',
        price_m: '1339,4',
        price_l: '1307,3',
        price_xl: '1278,0',
    },
    {
        image: '../images/image_69.png',
        name: 'Новогодний подарок "Бенгалия"',
        pack: 'жесть',
        weight: '1000',
        price_xs: '1294,0',
        price_s: '1255,4',
        price_m: '1220,4',
        price_l: '1188,3',
        price_xl: '1159,0',
    },
    {
        image: '../images/image_70.png',
        name: 'Новогодний подарок "Кейс Винтаж"',
        pack: 'жесть',
        weight: '1000',
        price_xs: '1294,0',
        price_s: '1255,4',
        price_m: '1220,4',
        price_l: '1188,3',
        price_xl: '1159,0',
    },
    {
        image: '../images/image_71.png',
        name: 'Новогодний подарок Кейс "Палех Тройка"',
        pack: 'жесть',
        weight: '1200',
        price_xs: '1563,0',
        price_s: '1517,5',
        price_m: '1476,1',
        price_l: '1438,3',
        price_xl: '1403,7',
    },
    {
        image: '../images/image_72.png',
        name: 'Новогодний подарок "Кейс Винтаж"',
        pack: 'жесть',
        weight: '1200',
        price_xs: '1444,0',
        price_s: '1398,5',
        price_m: '1357,1',
        price_l: '1319,3',
        price_xl: '1284,7',
    },
    {
        image: '../images/image_73.png',
        name: 'Новогодний подарок "Кейс "Зимний город" с игрой',
        pack: 'жесть',
        weight: '1200',
        price_xs: '1497,0',
        price_s: '1451,5',
        price_m: '1410,1',
        price_l: '1372,3',
        price_xl: '1337,7',
    },
    {
        image: '../images/image_74.png',
        name: 'Новогодний подарок "Кейс "Зимний город" с игрой',
        pack: 'жесть',
        weight: '1500',
        price_xs: '1716,0',
        price_s: '1660,3',
        price_m: '1609,7',
        price_l: '1563,5',
        price_xl: '1521,2',
    },
    {
        image: '../images/image_75.png',
        name: 'Новогодний подарок "Башмачок"',
        pack: 'мягкая игрушка',
        weight: '300',
        price_xs: '650,0',
        price_s: '639,8',
        price_m: '630,5',
        price_l: '622,1',
        price_xl: '614,3',
    },
    {
        image: '../images/image_76.png',
        name: 'Новогодний подарок "Сании"',
        pack: 'мягкая игрушка',
        weight: '500',
        price_xs: '894,0',
        price_s: '877,8',
        price_m: '863,1',
        price_l: '849,7',
        price_xl: '837,3',
    },
    {
        image: '../images/image_77.png',
        name: 'Новогодний подарок "Фани"',
        pack: 'мягкая игрушка',
        weight: '500',
        price_xs: '925,0',
        price_s: '908,8',
        price_m: '894,1',
        price_l: '880,7',
        price_xl: '868,3',
    },
    {
        image: '../images/image_78.png',
        name: 'Новогодний подарок "Звездун"',
        pack: 'мягкая игрушка',
        weight: '500',
        price_xs: '975,0',
        price_s: '958,8',
        price_m: '944,1',
        price_l: '930,7',
        price_xl: '918,3',
    },
    {
        image: '../images/image_79.png',
        name: 'Новогодний подарок "Джуно"',
        pack: 'мягкая игрушка',
        weight: '500',
        price_xs: '1 030,0',
        price_s: '1 013,8',
        price_m: '999,1',
        price_l: '985,7',
        price_xl: '973,3',
    },
    {
        image: '../images/image_80.png',
        name: 'Новогодний подарок "Брюс"',
        pack: 'мягкая игрушка',
        weight: '500',
        price_xs: '1 060,0',
        price_s: '1 043,8',
        price_m: '1 029,1',
        price_l: '1 015,7',
        price_xl: '1 003,3',
    },
    {
        image: '../images/image_81.png',
        name: 'Новогодний подарок "Звездун"',
        pack: 'мягкая игрушка',
        weight: '600',
        price_xs: '1 063,0',
        price_s: '1 042,7',
        price_m: '1 024,3',
        price_l: '1 007,4',
        price_xl: '992,0',
    },
    {
        image: '../images/image_82.png',
        name: 'Новогодний подарок "Шерхан"',
        pack: 'мягкая игрушка',
        weight: '600',
        price_xs: '1 268,0',
        price_s: '1 247,7',
        price_m: '1 229,3',
        price_l: '1 212,4',
        price_xl: '1 197,0',
    },
    {
        image: '../images/image_83.png',
        name: 'Новогодний подарок "Джуно"',
        pack: 'мягкая игрушка',
        weight: '600',
        price_xs: '1 118,0',
        price_s: '1 097,7',
        price_m: '1 079,3',
        price_l: '1 062,4',
        price_xl: '1 047,0',
    },
    {
        image: '../images/image_84.png',
        name: 'Новогодний подарок "Фани"',
        pack: 'мягкая игрушка',
        weight: '600',
        price_xs: '1 013,0',
        price_s: '992,7',
        price_m: '974,3',
        price_l: '957,4',
        price_xl: '942,0',
    },
    {
        image: '../images/image_85.png',
        name: 'Новогодний подарок "Брюс"',
        pack: 'мягкая игрушка',
        weight: '600',
        price_xs: '1 148,0',
        price_s: '1 127,7',
        price_m: '1 109,3',
        price_l: '1 092,4',
        price_xl: '1 077,0',
    },
    {
        image: '../images/image_86.png',
        name: 'Новогодний подарок "Флин"',
        pack: 'мягкая игрушка',
        weight: '600',
        price_xs: '1 118,0',
        price_s: '1 097,7',
        price_m: '1 079,3',
        price_l: '1 062,4',
        price_xl: '1 047,0',
    },
    {
        image: '../images/image_87.png',
        name: 'Новогодний подарок "Сэм"',
        pack: 'мягкая игрушка',
        weight: '700',
        price_xs: '1 163,0',
        price_s: '1 136,9',
        price_m: '1 113,1',
        price_l: '1 091,4',
        price_xl: '1 071,5',
    },
    {
        image: '../images/image_88.png',
        name: 'Новогодний подарок "Стинг"',
        pack: 'мягкая игрушка',
        weight: '700',
        price_xs: '1 179,0',
        price_s: '1 152,9',
        price_m: '1 129,1',
        price_l: '1 107,4',
        price_xl: '1 087,5',
    },
    {
        image: '../images/image_89.png',
        name: 'Новогодний подарок "Тигра',
        pack: 'мягкая игрушка',
        weight: '700',
        price_xs: '1 219,0',
        price_s: '1 192,9',
        price_m: '1 169,1',
        price_l: '1 147,4',
        price_xl: '1 127,5',
    },
    {
        image: '../images/image_90.png',
        name: 'Новогодний подарок "Шерхан"',
        pack: 'мягкая игрушка',
        weight: '700',
        price_xs: '1 393,0',
        price_s: '1 366,9',
        price_m: '1 343,1',
        price_l: '1 321,4',
        price_xl: '1 301,5',
    },
    {
        image: '../images/image_91.png',
        name: 'Новогодний подарок "Флин"',
        pack: 'мягкая игрушка',
        weight: '700',
        price_xs: '1 243,0',
        price_s: '1 216,9',
        price_m: '1 193,1',
        price_l: '1 171,4',
        price_xl: '1 151,5',
    },
    {
        image: '../images/image_92.png',
        name: 'Новогодний подарок "Дикси"',
        pack: 'мягкая игрушка',
        weight: '700',
        price_xs: '1 253,0',
        price_s: '1 226,9',
        price_m: '1 203,1',
        price_l: '1 181,4',
        price_xl: '1 161,5',
    },
    {
        image: '../images/image_93.png',
        name: 'Новогодний подарок "Пикси"',
        pack: 'мягкая игрушка',
        weight: '700',
        price_xs: '1 253,0',
        price_s: '1 226,9',
        price_m: '1 203,1',
        price_l: '1 181,4',
        price_xl: '1 161,5',
    },
    {
        image: '../images/image_94.png',
        name: 'Новогодний подарок "Тигра"',
        pack: 'мягкая игрушка',
        weight: '800',
        price_xs: '1 303,0',
        price_s: '1 273,0',
        price_m: '1 245,6',
        price_l: '1 220,7',
        price_xl: '1 197,8',
    },
    {
        image: '../images/image_95.png',
        name: 'Новогодний подарок "Фрида"',
        pack: 'мягкая игрушка',
        weight: '800',
        price_xs: '1 359,0',
        price_s: '1 329,0',
        price_m: '1 301,6',
        price_l: '1 276,7',
        price_xl: '1 253,8',
    },
    {
        image: '../images/image_96.png',
        name: 'Новогодний подарок "Шерхан"',
        pack: 'мягкая игрушка',
        weight: '800',
        price_xs: '1 477,0',
        price_s: '1 447,0',
        price_m: '1 419,6',
        price_l: '1 394,7',
        price_xl: '1 371,8',
    },
    {
        image: '../images/image_97.png',
        name: 'Новогодний подарок Рюкзак "Алекс"',
        pack: 'мягкая игрушка',
        weight: '800',
        price_xs: '1 382,0',
        price_s: '1 352,0',
        price_m: '1 324,6',
        price_l: '1 299,7',
        price_xl: '1 276,8',
    },
    {
        image: '../images/image_98.png',
        name: 'Новогодний подарок "Тигра',
        pack: 'мягкая игрушка',
        weight: '900',
        price_xs: '1 421,0',
        price_s: '1 385,4',
        price_m: '1 353,1',
        price_l: '1 323,6',
        price_xl: '1 296,5',
    },
    {
        image: '../images/image_99.png',
        name: 'Новогодний подарок "Алекс"',
        pack: 'мягкая игрушка',
        weight: '900',
        price_xs: '1 500,0',
        price_s: '1 464,4',
        price_m: '1 432,1',
        price_l: '1 402,6',
        price_xl: '1 375,5',
    },
    {
        image: '../images/image_100.png',
        name: 'Новогодний подарок "Спайк"',
        pack: 'мягкая игрушка',
        weight: '1000',
        price_xs: '1 686,0',
        price_s: '1 647,4',
        price_m: '1 612,4',
        price_l: '1 580,3',
        price_xl: '1 551,0',
    },
    {
        image: '../images/image_101.png',
        name: 'Новогодний подарок Рюкзак "Обнимашкин"',
        pack: 'мягкая игрушка',
        weight: '1000',
        price_xs: '1 294,0',
        price_s: '1 255,4',
        price_m: '1 220,4',
        price_l: '1 188,3',
        price_xl: '1 159,0',
    },
    {
        image: '../images/image_102.png',
        name: 'Новогодний подарок "Алекс"',
        pack: 'мягкая игрушка',
        weight: '1000',
        price_xs: '1 565,0',
        price_s: '1 526,4',
        price_m: '1 491,4',
        price_l: '1 459,3',
        price_xl: '1 430,0',
    }
]

export const grid = document.querySelector('.grid');